const arrayFilm=[
    {
        id:1,
        title:"KUNG FU PANDA 4",
        intro:"Sau khi Po được chọn trở thành Thủ lĩnh tinh thần của Thung lũng Hòa bình, Po cần tìm và huấn luyện một Hiệp Sĩ Rồng mới, trong khi một nữ phù thủy quyền năng đan lên kế hoạch triệu tập lại tất cả những kẻ phản diện bậc thầy mà Po đã đánh bại trước đây.",
        phanLoai:"Phân loại: Phim phổ biến với mọi độ tuổi",
        daoDien:"Đạo diễn: Mike Mitchell, Stephanie Stine",
        dienVien:"Diễn viên: Angelina Jolie, Ke Huy Quan",
        theLoai:"Thể loại: Animation",
        khoiChieu:"Khởi chiếu:08/03/2024",
        thoiLuong:"Thời lượng: 95 phút",
        ngonNgu:"Ngôn ngữ:Phụ đề/Lồng tiếng",
        image:"./access/img/kunfu.jpg",
        video:"./access/video/kungfupanda.mp4",
    },
    {
        id:2,
        title:"EXHUMA",
        intro:"Một pháp sư được cấp một số tiền lớn để di dời một ngôi mộ. Anh ấy di chuyển cùng với người bạn đồng hành của mình, Ji Gwan.",
        phanLoai:"Phân loại: Phim phổ biến với 16 tuổi đổ lên",
        daoDien:"Đạo diễn: Jae-hyun Jang",
        dienVien:"Diễn viên: Lee Do-hyun, Choi Min-sik",
        theLoai:"Thể loại: Horror",
        khoiChieu:"Khởi chiếu: 16/03/2024",
        thoiLuong:"Thời lượng: 133 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/quatmotrungma.jpg",
        video:"./access/video/exhuma.mp4"
    },
    {
        id:3,
        title:"DEMON SLAYER: TO THE HASHIRA TRAINING",
        intro:"Lấy bối cảnh ở làng thợ rèn và hồi kết của trận ác chiến giữa Tanjiro với Thượng Huyền Tứ Hantengu và việc Nezuko khắc chế được mặt trời. Tập đầu tiên của phần Đại Trụ.Đặc Huấn, mở màn cho khóa đặc huấn của các Đại Trụ cho cuộc quyết chiến với Kibutsuji.",
        phanLoai:"Phân loại: Phim phổ biến với 13 tuổi đổ lên",
        daoDien:"Đạo diễn: ĐaS.J. Clarkson",
        dienVien:"Diễn viên: Sydney Sweeney, Adam Scott",
        theLoai:"Thể loại: Animation",
        khoiChieu:"Khởi chiếu: 14/02/2024",
        thoiLuong:"Thời lượng: 116 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề/Lồng tiếng",
        image:"./access/img/madame.jpg",
        video:"./access/video/demonslayder.mp4"
    },
    {
        id:4,
        title:"SÁNG ĐÈN",
        intro:"Hành trình nhiều thăng hoa nhưng cũng đầy biến cố hài hước của đoàn cải lương Viễn Phương khi phải biến tấu từ một đoàn cải lương chính thống trở thành đoàn tạp kỹ với xiếc, lô tô và tân nhạc.",
        phanLoai:"Phân loại: Phim được phổ biến đến người xem dưới 13 tuổi với điều kiện xem cùng cha, mẹ hoặc người giám hộ",
        daoDien:"Đạo diễn: Hoang Tuan Cuong",
        dienVien:"Diễn viên: Bach Cong Khanh, NSUT Huu Chau",
        theLoai:"Thể loại: Romance",
        khoiChieu:"Khởi chiếu: 22/03/2024",
        thoiLuong:"Thời lượng: 128 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/sang_den.jpg",
        video:"./access/video/sangden.mp4"
    },
    {
        id:5,
        title:"QUÝ CÔ THỪA KẾ 2",
        intro:"Mộ phim kể về gia đình tưởng chừng như đầm ấm và hạnh phúc của Cao Minh, Hải Đường và con gái Kim. Tuy nhiên, mọi thứ ngày càng trở nên kì lạ khi Cao Minh càng lúc càng thô bạo và có xu hướng kiểm soát đầy độc hại lên cả vợ và con gái mình.",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 16 tuổi trở lên",
        daoDien:"Đạo diễn: Hoàng Duy",
        dienVien:"Diễn viên: Trang Nhung, Otis Nhật Trường, Huy Khánh, Lâm Vỹ Dạ",
        theLoai:"Thể loại: Drama",
        khoiChieu:"Khởi chiếu: 08/03/2024",
        thoiLuong:"Thời lượng: 118 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/referenceSchemeHeadOfficeallowPlaceHoldertrueheight700ldapp-1.jpg",
        video:"./access/video/quycothuake.mp4"
    },
    {
        id:6,
        title:"MOEI: THE PROMISSED",
        intro:"Người cha quá cố đã phản bội lời thề khiến cho hồn ma Nang Rum nổi giận, quyết trả báo ứng lên người August bắt cầu đền mạng để chuộc tội . August sẽ tìm ra được lời thề để hóa giải lỗi lầm hay phải trả giá bằng tính mạng của bản thân?",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 16 tuổi trở lên",
        daoDien:"Đạo diễn: Ekachai Sriwichai",
        dienVien:"Diễn viên: Ekachai Sriwichai, Siwat Chotichaicharin",
        theLoai:"Thể loại: Horror",
        khoiChieu:"Khởi chiếu: 22/03/2024",
        thoiLuong:"Thời lượng: 93 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/moei.jpg",
        video:"./access/video/denmang.mp4",

    },
    {
        id:7,
        title:"GODZILLA X KONG: THE NEW EMPIRE",
        intro:"Kong và Godzilla – hai sinh vật vĩ đại huyền thoại, hai kẻ thủ truyền kiếp sẽ cùng bắt tay thực thi một sứ mệnh chung mang tính sống còn để bảo vệ nhân loại, và trận chiến gắn kết chúng với loài người mãi mãi sẽ bắt đầu.",
        phanLoai:"Phân loại: Phim được phổ biến đến người xem dưới 13 tuổi với điều kiện xem cùng cha, mẹ hoặc người giám hộ",
        daoDien:"Đạo diễn: Adam Wingard",
        dienVien:"Diễn viên: Dan Stevens, Rebecca Hall",
        theLoai:"Thể loại: Action",
        khoiChieu:"Khởi chiếu: 29/03/2024",
        thoiLuong:"Thời lượng: 115 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/kong.jpg",
        video:"./access/video/kong.mp4",
    },
    {
        id:8,
        title:"18X2 BEYOND YOUTHDAY DAYS",
        intro:"Một chút thanh xuân nồng nhiệt thêm nhiều chút day dứt về tình đầu tất cả đều có trong Thanh Xuân 18×2: Lữ Trình Hướng Về Em.",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 13 tuổi trở lên",
        daoDien:"Đạo diễn: Mochihito Fujii",
        dienVien:"Diễn viên: Hứa Quang Hán, Shunsuke Michieda",
        theLoai:"Thể loại: Romance",
        khoiChieu:"Khởi chiếu: 12/04/2024",
        thoiLuong:"Thời lượng: 123 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/18x2.jpg",
        video:"./access/video/18x2.mp4",
    },
    {
        id:9,
        title:"NHÀ GIA TIÊN",
        intro:"Tại sao chúng ta phải cùng nhau gìn giữ căn Nhà Gia Tiên? Vì sao những thế hệ con cháu luôn mất kết nối với ông bà của mình? Con người khi chết sẽ đi về đâu? Tại sao mỗi năm chúng ta phải làm đám giỗ cho người đã khuất?",
        daoDien:"Đạo diễn: Huỳnh Lập",
        dienVien:"Diễn viên: ",
        theLoai:"Thể loại: Mystery",
        khoiChieu:"Khởi chiếu: 01/12/2024",
        thoiLuong:"Thời lượng: 100 phút",
        image:"./access/img/giatien.jpg",
    },
    {
        id:10,
        title:"LAT MAT 7: MOT DIEU UOC",
        intro:"Bộ phim 'chữa lành' lấy cảm hứng từ những câu chuyện thường nhật trong đời sống gia đình. Câu chuyện xoay quanh một người mẹ và những đứa con với tựa 'Một Điều Ước'.",
        daoDien:"Đạo diễn: Lý Hải",
        dienVien:"Diễn viên: Thái Vũ, Trương Minh Cường, Tín Nguyễn",
        theLoai:"Thể loại: Healing",
        khoiChieu:"Khởi chiếu: 26/04/2024",
        thoiLuong:"Thời lượng: 110 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/lm7.png",
        
    },
    {
        id:11,
        title:"CÁI GIÁ CỦA HẠNH PHÚC",
        intro:"Bà Dương và ông Thoại luôn cố gắng để xây dựng một hình ảnh gia đình tài giỏi và danh giá trong mắt mọi người. Tuy nhiên dưới lớp vỏ bọc hào nhoáng ấy là những biến cố và lục đục gia đình đầy sóng gió. Nhìn kĩ hơn một chút bức tranh gia đình hạnh phúc ấy.",
        daoDien:"Đạo diễn: Nguyễn Ngọc Lâm",
        dienVien:"Diễn viên: Lâm Thanh Nhã, Hữu Châu, Xuân Lan, Thái Hòa, Uyển Ân",
        theLoai:"Thể loại: Drama",
        khoiChieu:"Khởi chiếu: 26/04/2024",
        thoiLuong:"Thời lượng: 110 phút",
        image:"./access/img/caigiacuahanhphuc.jpg",
        
    },
    {
        id:12,
        title:"B4S TRƯỚC GIỜ YÊU",
        intro:"Tại một quán bar, một nhóm bạn trò chuyện về quan điểm chuyện yêu.",
        daoDien:"Đạo diễn: Tùng Leo",
        dienVien:"Diễn viên: Jun Vũ, Vinh Râu",
        theLoai:"Thể loại: Drama",
        khoiChieu:"Khởi chiếu: 05/04/2024",
        thoiLuong:"Thời lượng: 100 phút",
        image:"./access/img/omen.jpg",
    },
    {
        id:13,
        title:"LUCA",
        intro:"'Mùa Hè Của Luca'kể về chuyến hành trình của cậu bé Luca tại hòn đảo Portorosso thuộc vùng biển Địa Trung Hải ở Ý tuyệt đẹp. Ở đây cậu đã làm quen và kết thân với những người bạn nhỏ mới và tận hưởng mùa hè đầy nắng, kem Gelato và cả món mì Ý trứ danh.",
        daoDien:"Đạo diễn: Enrico Casarosa",
        dienVien:"Diễn viên: Jacob Tremblay, Jack Dylan Grazer",
        theLoai:"Thể loại: Animation",
        khoiChieu:"Khởi chiếu: 19/04/2024",
        thoiLuong:"Thời lượng: 100 phút",
        image:"./access/img/luca.jpg",
    },
    {
        id:14,
        title:"WANNABE",
        intro:"Một nữ diễn viên đang chuẩn bị quay trở lại diễn xuất sau một thời gian dài gián đoạn thì bị cuốn vào một sự cố bất ngờ và lao thẳng vào thảm họa.",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 18 tuổi trở lên",
        daoDien:"Đạo diễn: Young-sun Yoo",
        dienVien:"Diễn viên: Park Ji-yeon, Ji-eun Song",
        theLoai:"Thể loại: Crime",
        khoiChieu:"Khởi chiếu: 12/04/2024",
        thoiLuong:"Thời lượng: 102 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/wanabe.jpg",
        video:"./access/video/wannabe.mp4",
    },
    {
        id:15,
        title:"CIVIL WAR",
        intro:"Một cuộc hành trình xuyên qua tương lai đen tối của nước Mỹ, theo chân một nhóm nhà báo gắn bó với quân đội khi họ chạy đua với thời gian để đến DC trước khi các phe phái nổi dậy tràn vào Nhà Trắng.",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 18 tuổi trở lên",
        daoDien:"Đạo diễn: Alex Garland",
        dienVien:"Diễn viên: Kirsten Dunst,Wagner Moura",
        theLoai:"Thể loại: Action",
        khoiChieu:"Khởi chiếu: 12/04/2024",
        thoiLuong:"Thời lượng: 102 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/war.jpg",
        video:"./access/video/war.mp4",
    },
    {
        id:16,
        title:"MOBILE SUIT GUNDAM SEED FREEDOM",
        intro:"C.E. (Cosmic Era) 75, trận chiến vẫn chưa kết thúc, với phong trào độc lập nổi lên và cuộc xâm lược của Blue Cosmos, một nhóm kêu gọi trục xuất Điều phối viên. Để xoa dịu tình hình, tổ chức giám sát hòa bình thế giới 'Compass' được thành lập.",
        phanLoai:"Phân loại: Phim phổ biến đến người xem từ 13 tuổi trở lên",
        daoDien:"Đạo diễn: Mitsuo Fukuda",
        dienVien:"Diễn viên: Yuichi Nakamura, Stephanie Sheh",
        theLoai:"Thể loại: Anime",
        khoiChieu:"Khởi chiếu: 10/03/2024",
        thoiLuong:"Thời lượng: 125 phút",
        ngonNgu:"Ngôn ngữ: Phụ đề",
        image:"./access/img/gumdam.jpg",
        video:"./access/video/gumdam.mp4",
    },
]
        localStorage.setItem("films", JSON.stringify(arrayFilm)); 